### ISSUE TITLE
Who is behind the Open XiangShan team? can you please tell us more 

### ISSUE THREAD

**Issue by ghost** [OpenXiangShan/openxiangshan.github.io#1]
Who is behind the Open XiangShan team? can you please tell us more.
And how to join and practice?

**Comment by poemonsense** [comment]
XiangShan is an open-source high-performance RISC-V processor, maintained by Institute of Computing Technology, Chinese Academy of Sciences.

Visit https://github.com/OpenXiangShan/XiangShan for more information.
